name: Build and Deploy Masterchef API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Run tests
        run: mvn test

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: masterchef-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar

