name: CI/CD MasterChef App

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        working-directory: Masterchef
        run: mvn clean test

 
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: Masterchef
        run: mvn clean package -DskipTests=false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: masterchef-dosw
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Masterchef/target/*.jar
