name: CI/CD Masterchef

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Clonar repositorio
        uses: actions/checkout@v4

      - name: ☕ Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Instalar dependencias y ejecutar pruebas
        run: mvn clean test

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: 🧱 Clonar repositorio
        uses: actions/checkout@v4

      - name: ☕ Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🧰 Empaquetar aplicación
        run: mvn clean package -DskipTests

      - name: 🚀 Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: masterchef-api      
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
